# coding=UTF-8

#função para gerar arquivo txt, salvando no diretório e dados passados por parâmetros (dados_arquivo é um dicionário com os parâmetros)
def gera_arquivo(diretorio, dados_arquivo):
	arquivo = open(diretorio, 'w')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('início de execução: '+str(dados_arquivo['time_begin'])+' - fim de execução: '+str(dados_arquivo['time_end'])+'\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('Configuração de execução'+'\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('Estratégia: '+dados_arquivo['estrategia']+'\n')
	arquivo.write('Tamanho da janela: '+str(dados_arquivo['tamanho_janela'])+'\n')
	arquivo.write('Posição do rotulo: '+dados_arquivo['rotulo']+'\n')
	arquivo.write('Tipo de caracteristica: '+str(dados_arquivo['tipo_caracteristica'])+'\n')
	arquivo.write('Caracteristica: '+str(dados_arquivo['caracteristica'])+'\n')
	arquivo.write('Ponto de articulação: '+str(dados_arquivo['ponto_articulacao'])+'\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('Parâmetros do SVM\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('Kernel: '+dados_arquivo['kernel']+'\n')
	arquivo.write('C: '+str(dados_arquivo['c'])+'\n')
	arquivo.write('Gamma: '+str(dados_arquivo['gamma'])+'\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('Informações de treino e teste\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('Tabelas de treino: '+str(dados_arquivo['tabela_treino'])+'\n')
	arquivo.write('Tamanho do treino: '+str(dados_arquivo['tamanho_treino'])+'\n' )
	arquivo.write('Tabelas de teste: '+str(dados_arquivo['tabela_teste'])+'\n')
	arquivo.write('Tamanho do teste: '+str(dados_arquivo['tamanho_teste'])+'\n' )
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('Matriz de confusão mult-classe:\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write(repr(dados_arquivo['matriz_confusao_mc'])+'\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('(precisão) descanso - preparação - hold - stroke - retração: '+str(dados_arquivo['precisao_mc'])+'\n')
	arquivo.write('(revocação) descanso - preparação - hold - stroke - retração: '+str(dados_arquivo['revocacao_mc'])+'\n')
	arquivo.write('(f-score) descanso - preparação - hold - stroke - retração: '+str(dados_arquivo['f_score_mc'])+'\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('Matriz de descanso:\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write(repr(dados_arquivo['matriz_d'])+'\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('precisão (D): '+str(dados_arquivo['precisao_d'])+'\n')
	arquivo.write('revocação (D): '+str(dados_arquivo['revocacao_d'])+'\n')
	arquivo.write('f-score (D): '+str(dados_arquivo['f_score_d'])+'\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('Matriz de preparação:\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write(repr(dados_arquivo['matriz_p'])+'\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('precisão (P): '+str(dados_arquivo['precisao_p'])+'\n')
	arquivo.write('revocação (P): '+str(dados_arquivo['revocacao_p'])+'\n')
	arquivo.write('f-score (P): '+str(dados_arquivo['f_score_p'])+'\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('Matriz de hold:\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write(repr(dados_arquivo['matriz_h'])+'\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('precisão (H): '+str(dados_arquivo['precisao_h'])+'\n')
	arquivo.write('revocação (H): '+str(dados_arquivo['revocacao_h'])+'\n')
	arquivo.write('f-score (H): '+str(dados_arquivo['f_score_h'])+'\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('Matriz de stroke:\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write(repr(dados_arquivo['matriz_s'])+'\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('precisão (S): '+str(dados_arquivo['precisao_s'])+'\n')
	arquivo.write('revocação (S): '+str(dados_arquivo['revocacao_s'])+'\n')
	arquivo.write('f-score (S): '+str(dados_arquivo['f_score_s'])+'\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('Matriz de retração:\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write(repr(dados_arquivo['matriz_r'])+'\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('precisão (R): '+str(dados_arquivo['precisao_r'])+'\n')
	arquivo.write('revocação (R): '+str(dados_arquivo['revocacao_r'])+'\n')
	arquivo.write('f-score (R): '+str(dados_arquivo['f_score_r'])+'\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	arquivo.write('Saídas da svm:\n')
	arquivo.write('----------------------------------------------------------------------------------------------------------\n')
	saidas_svm = dados_arquivo['saidas_svm']
	for i,saida in enumerate(saidas_svm):
		if (i == 0):
			for s in saida:
				arquivo.write(s)
				arquivo.write(',')
			arquivo.write('\n')
		if (i > 0):
			for s in saida:
				arquivo.write(repr(s))
				arquivo.write(',')
			arquivo.write('\n')
	arquivo.close